# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python: "3.5"

script: tox

install:
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
